# Generated by Django 2.0.1 on 2018-01-27 08:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_webtoon_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=''),
        ),
    ]
